name: Post-Release Actions

on:
  release:
    types:
      - created
      - published

jobs:
  update-docs-release-notes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout react-native-expo
        uses: actions/checkout@v6
        with:
          path: react-native-expo
      - name: Checkout docs
        uses: actions/checkout@v6
        with:
          repository: smileidentity/docs
          path: docs
          token: ${{ secrets.GH_PAT }}
      - name: Copy CHANGELOG.md to Release Notes
        run: cp react-native-expo/CHANGELOG.md docs/integration-options/mobile/react-native-expo-v11/release-notes.md
      - name: Create docs PR
        uses: peter-evans/create-pull-request@v8
        with:
          token: ${{ secrets.GH_PAT }}
          path: docs
          commit-message: React Native Expo ${{ github.event.release.tag_name }} Release Notes
          title: React Native Expo ${{ github.event.release.tag_name }} Release Notes
          body: Automated PR to update the release notes
          branch: react-native-expo-release-notes-${{ github.event.release.tag_name }}
          labels: "release-notes"
          team-reviewers: "smileidentity/mobile"
